apps/events/urls.py
from django.urls import path

from apps.events import views

urlpatterns = [
    path("events/", views.get_events, name="events"),
    path("events/<str:event_id>/", views.get_event, name="event-detail"),
    path(
        "events/<str:event_id>/register/",
        views.register_event_member,
        name="register-event-member",
    ),
    path(
        "events/<str:event_id>/unregister/",
        views.unregister_event_member,
        name="unregister-event-member",
    ),
    path("librarian/events/", views.librarian_get_events, name="librarian-events"),
    path(
        "librarian/events/<str:event_id>/update/",
        views.update_event,
        name="update-event",
    ),
    path(
        "librarian/events/<str:event_id>/delete/",
        views.delete_event,
        name="delete-event",
    ),
    path("librarian/events/add/", views.create_event, name="add-event"),
]

somo_lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("apps.users.urls")),
    path("", include("apps.core.urls")),
    path("", include("apps.books.urls")),
    path("", include("apps.members.urls")),
    path("", include("apps.transactions.urls")),
    path("", include("apps.reservations.urls")),
    path("", include("apps.notifications.urls")),
    path("", include("apps.librarians.urls")),
    path("", include("apps.events.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/events/models.py
from django.db import models

from apps.utils.base import BaseModel
from apps.members.models import Member


class Event(BaseModel):

    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to="events/%Y%m%d")
    max_participants = models.IntegerField(default=50)
    current_participants = models.IntegerField(default=0)
    event_date = models.DateField()

    class Meta:
        verbose_name_plural = "Events"
        ordering = ["-event_date"]

    def __str__(self):
        return f"{self.name} - {self.event_date}"


class EventRegistration(BaseModel):

    class Status(models.TextChoices):
        REGISTERED = "Registered", "Registered"
        ATTENDED = "Attended", "Attended"
        CANCELLED = "Cancelled", "Cancelled"

    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    participant = models.ForeignKey(
        Member, related_name="event_member", on_delete=models.CASCADE
    )
    registration_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=255, choices=Status, default=Status.REGISTERED)

    class Meta:
        verbose_name_plural = "Registrations"
        ordering = ["-registration_date"]

    def __str__(self):
        return f"{self.participant} - {self.event}"

apps/events/forms.py
from django import forms

from apps.events.models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            "name",
            "location",
            "description",
            "image",
            "max_participants",
            "event_date",
        ]

    name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    location = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    description = forms.CharField(
        required=True, widget=forms.Textarea(attrs={"class": "form-control"})
    )
    image = forms.ImageField(
        required=True,
        widget=forms.FileInput(attrs={"class": "form-control-file"}),
    )
    max_participants = forms.IntegerField(
        required=True, widget=forms.NumberInput(attrs={"class": "form-control"})
    )
    event_date = forms.DateTimeField(
        required=True,
        widget=forms.DateTimeInput(
            attrs={"class": "form-control", "type": "datetime-local"}
        ),
    )

apps/events/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages

from apps.utils.permissions import is_librarian, is_member
from apps.events.models import Event, EventRegistration
from apps.events.forms import EventForm
from apps.members.models import Member


def get_events(request, *args, **kwargs):
    # Fetch all events from the database
    event_list = Event.objects.all()

    # paginate events
    paginator = Paginator(event_list, 15)
    page_number = request.GET.get("page")
    events = paginator.get_page(page_number)

    return render(request, "events.html", {"events": events})


def get_event(request, *args, **kwargs):
    # Fetch a specific event from the database
    event = Event.objects.filter(pk=kwargs.get("event_id")).first()
    member = None

    if request.user.is_authenticated:
        member = Member.objects.filter(user=request.user).first()
    # check if member is already a participant
    is_participant = EventRegistration.objects.filter(participant=member).exists()

    if event is None:
        return redirect("events")
    return render(
        request, "event_detail.html", {"event": event, "is_participant": is_participant}
    )


@login_required
@is_member
def register_event_member(request, *args, **kwargs):
    # Register a user for an event by id
    event = Event.objects.filter(id=kwargs.get("event_id")).first()
    member = Member.objects.filter(user=request.user).first()
    if event is None:
        messages.error(request, "Event not found.")
        return redirect("events")

    # check if member is already registered
    if EventRegistration.objects.filter(participant=member).exists():
        messages.error(request, "You have already registered for this event.")
        return redirect("event-detail", event_id=event.id)

    event_registration = EventRegistration.objects.create(
        event=event, participant=member
    )
    event.current_participants = event.current_participants + 1
    event.save()

    messages.success(request, "Registration successful!")
    return redirect("event-detail", event_id=event.id)


@login_required
@is_member
def unregister_event_member(request, *args, **kwargs):
    # Unregister a user for an event by id
    event = Event.objects.filter(id=kwargs.get("event_id")).first()
    member = Member.objects.filter(user=request.user).first()
    if event is None:
        messages.error(request, "Event not found.")
        return redirect("events")
    if not EventRegistration.objects.filter(participant=member, event=event).exists():
        messages.error(request, "You are not registered for this event.")
        return redirect("event-detail", event_id=event.id)
    event_registration = EventRegistration.objects.filter(
        participant=member, event=event
    ).first()
    event_registration.delete()
    event.current_participants = (
        event.current_participants - 1 if event.current_participants >= 1 else 0
    )
    event.save()
    messages.success(request, "Unregistered from the event successfully!")
    return redirect("event-detail", event_id=event.id)


@login_required
@is_librarian
def librarian_get_events(request, *args, **kwargs):
    # Fetch all events from the database
    event_list = Event.objects.all()
    # paginate events
    paginator = Paginator(event_list, 15)
    page_number = request.GET.get("page")
    events = paginator.get_page(page_number)
    return render(request, "librarian_events.html", {"events": events})


@login_required
@is_librarian
def create_event(request, *args, **kwargs):
    # Add a new event to the database
    if request.method == "POST":
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Event added successfully!")
            return redirect("librarian-events")
        else:
            messages.error(request, "Book not added. Please check the form.")
            return render(request, "create_event.html", {"form": form})
    form = EventForm()
    return render(request, "create_event.html", {"form": form})


@login_required
@is_librarian
def update_event(request, *args, **kwargs):
    # Update an existing event in the database by id
    event = Event.objects.filter(id=kwargs.get("event_id")).first()
    if event is None:
        messages.error(request, "Event not found.")
        return redirect("librarian-events")
    if request.method == "POST":
        form = EventForm(request.POST, request.FILES, instance=event)
        if form.is_valid():
            form.save()
            messages.success(request, "Event updated successfully!")
            return redirect("librarian-events")
    form = EventForm(instance=event)
    return render(request, "update_event.html", {"form": form})


@login_required
@is_librarian
def delete_event(request, *args, **kwargs):
    # Delete an event from the database by id
    event_id = kwargs.get("event_id")
    event = Event.objects.filter(pk=event_id).first()
    if event is None:
        messages.error(request, "Event not found.")
        return redirect("librarian-events")

    event.delete()
    messages.success(request, "Event deleted successfully!")
    return redirect("librarian-events")

apps/events/templates/create_event.html
{% extends "librarian_dashboard.html" %} {% block main_content %}
{% include "dashboard_header.html" with title="Add Event" %}

<form
  method="POST"
  enctype="multipart/form-data"
  class="card p-4"
>
{% if form.errors %}
<div class="alert alert-danger">
  <strong>There were some errors with your submission:</strong>
  <ul>
    {% for field in form %} {% for error in field.errors %}
    <li>{{ field }} {{ error }}</li>
    {% endfor %} {% endfor %}
  </ul>
</div>
{% endif %} 
  {% csrf_token %}
  <div class="mb-3">
    <label for="id_name" class="form-label">Event Name</label>
    {{ form.name }}
  </div>
  <div class="mb-3">
    <label for="id_location" class="form-label">Location</label>
    {{ form.location }}
  </div>
  <div class="mb-3">
    <label for="id_description" class="form-label">Description</label>
    {{ form.description }}
  </div>
  <div class="mb-3">
    <label for="id_image" class="form-label">Event Image</label>
    {{ form.image }}
  </div>
  <div class="mb-3">
    <label for="id_max_participants" class="form-label">Max Participants</label>
    {{ form.max_participants }}
  </div>
  <div class="mb-3">
    <label for="id_event_date" class="form-label">Event Date</label>
    {{ form.event_date }}
  </div>
  <button type="submit" class="btn btn-save">Add Event</button>
</form>
{% endblock main_content %}

apps/events/templates/event_detail.html
{% extends "base.html" %}
{% load static %} 
{% block content %}

{% include "custom_navbar.html" %}

<div class="container mt-2">
  <a href="{% url "events" %}" class="btn btn-save mb-3">
    <i class="fas fa-arrow-left"></i> Back to Events
  </a>

  <div class="card mb-5">
    <div class="row g-0">
      <div class="col-md-4 text-center p-3">
        {% if event.image %}
        <img src="{{ event.image.url }}" class="card-img-top" alt="Event Image" />
        {% else %}
        <img src="https://placehold.co/800x600" class="card-img-top" alt="Event Image" />
        {% endif %}
      </div>

      <div class="col-md-8">
        <div class="card-body">
          <h1 class="card-title fw-bold">{{ event.name }}</h1>
          <p class="card-text"><strong>Location:</strong> {{ event.location }}</p>
          <p class="card-text"><strong>Event Date:</strong> {{ event.event_date }}</p>
          <p class="card-text"><strong>Max Participants:</strong> {{ event.max_participants }}</p>
          <p class="card-text"><strong>Currently Registered:</strong> {{ event.current_participants }}</p>
          <p class="card-text"><strong>Description:</strong></p>
          <p class="card-text">{{ event.description|safe }}</p>


          {% if user.is_authenticated %}
            {% if  is_participant %}
               <p class="text-success"><i class="fas fa-check"></i> You are already registered for this event.</p>
               <a href="{% url 'unregister-event-member' event_id=event.id %}" class="btn btn-danger">
                <i class="fas fa-user-minus"></i> Unregister
              </a>
            {% elif event.current_participants < event.max_participants %}
              <a href="{% url 'register-event-member' event_id=event.id %}" class="btn btn-save">
                <i class="fas fa-user-plus"></i> Register
              </a>
            {% else %}
              <button class="btn btn-secondary" disabled>
                <i class="fas fa-ban"></i> Event Full
              </button>
            {% endif %}
          {% else %}
            <p class="text-danger"><i class="fas fa-info-circle"></i> Log in to register for this event.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

apps/events/templates/events.html
{% extends "base.html" %} {% block content %}

{% include "custom_navbar.html" %}
<div class="container mt-4">
  <div class="row mb-5">
    <!-- Main Content -->
    <div class="col-md-12">
      <!-- Book Listings -->
      {% if events %}
      <div class="row w-100">
        {% for event in events %}
        <a  href="{% url "event-detail" event_id=event.id %}" class="col-md-3 card book-card mb-3 text-decoration-none" style="height: auto !important;">
            {% if event.image %}
              <img
                src="{{ event.image.url }}"
                alt="Book Cover"
              />
            {% else %}
              <img
                src="https://placehold.co/600x400"
                class="card-img-top"
                alt="Book Cover"
              />
            {% endif %}
            <div class="card-body">
              <h4 class="card-title">{{ event.name|capfirst }}</h4>
              <p class="card-text"> {{ event.description|slice:":50" }}... </p>
              <p class="card-text">Location: {{ event.location }}</p>
              <p class="card-text">Date: {{ event.event_date }}</p>
            </div>
          </a>
        {% endfor %}   
      </div>
      {% else %}
      <div class="row">
          <div class="col-md-12 text-center mt-4">
            <h3>No events currently.</h3>
          </div>
      </div>
      {% endif %}  
      <nav aria-label="Page navigation" class="mt-4 d-flex justify-content-end">
        <ul class="pagination">
          <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          {% for num in events.paginator.page_range %}
          <li class="page-item {% if events.number == num %}is-active{% endif %}">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
          {% endfor %}
          <li class="page-item">
            <a class="page-link" href="?page={{ events.paginator.end_index|add:"1" }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
</div>


{% endblock content %}

apps/events/templates/librarian_events.html
{% extends "librarian_dashboard.html"%} {% block main_content%}

{% include "dashboard_header.html" with title="Events" %}

<div class="d-flex justify-content-end mb-3">
  <a href="{% url "add-event" %}" class="btn btn-save btn-md">
      <i class="fas fa-plus"></i> Add Event
  </a>
</div>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Location</th>
            <th>Description</th>
            <th>Image</th>
            <th>Max Participants</th>
            <th>Current Participants</th>
            <th>Event Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% if events %}
        {% for event in events %}
        <tr>
            <td>{{ event.name }}</td>
            <td>{{ event.location }}</td>
            <td>{{ event.description|slice:":50" }}</td>
            <td><img src="{{ event.image.url }}" alt="Event Image" height="60" width="60" class="event-image"></td>
            <td>{{ event.max_participants }}</td>
            <td>{{ event.current_participants }}</td>
            <td>{{ event.event_date }}</td>
            <td>
              <a href="{% url 'update-event' event_id=event.id %}" class="btn btn-warning btn-sm"
                ><i class="fas fa-edit"></i
              ></a>
              <button id="deleteEventBtn" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal" data-id="{{ event.id }}"><i class="fas fa-trash"></i> Delete</button>
            </td>
          </tr>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="7" class="text-center">No events found.</td>
        </tr>
        {% endif %}
    </tbody>
</table>
<nav aria-label="Page navigation" class="d-flex justify-content-end">
  <ul class="pagination">
    {% if events.has_previous %}
    <li class="page-item">
      <a
        class="page-link"
        href="?page={{ events.previous_page_number }}"
        aria-label="Previous"
      >
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %} {% for num in events.paginator.page_range %}
    <li class="page-item {% if events.number == num %}is-active{% endif %}">
      <a class="page-link" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% endfor %} {% if events.has_next %}
    <li class="page-item">
      <a
        class="page-link"
        href="?page={{ events.next_page_number }}"
        aria-label="Next"
      >
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endblock main_content%}

apps/events/templates/update_event.html
{% extends "librarian_dashboard.html" %} {% block main_content %}

{% include "dashboard_header.html" with title="Update Event" %}

<form method="POST" enctype="multipart/form-data" class="card p-4">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_name" class="form-label">Event Name</label>
        {{ form.name }}
    </div>
    <div class="mb-3">
        <label for="id_location" class="form-label">Location</label>
        {{ form.location }}
    </div>
    <div class="mb-3">
        <label for="id_description" class="form-label">Description</label>
        {{ form.description }}
    </div>
    <div class="mb-3">
        <label for="id_image" class="form-label">Event Image</label>
        {{ form.image }}
    </div>
    <div class="mb-3">
        <label for="id_max_participants" class="form-label">Max Participants</label>
        {{ form.max_participants }}
    </div>
    <div class="mb-3">
        <label for="id_event_date" class="form-label">Event Date</label>
        {{ form.event_date }}
    </div>
    <button type="submit" class="btn btn-primary">Update Event</button>
</form>
</div>

{% endblock main_content %}